# Two-tier processing architecture test configuration
# Usage: docker compose -f docker-compose.yaml -f compose_overrides/two-tier.yaml up -d --build
#
# This override tests the two-tier DaemonSet → StatefulSet architecture:
#
#   metrics-generator → otel-collector → tier1-a/b/c (DaemonSet pre-processing)
#                                           ↓
#                                     tier2-a/b (StatefulSet global aggregation)
#                                           ↓
#                                     victoriametrics
#
# Tier 1 (3 instances): Label normalization, adaptive downsampling, metric dropping
# Tier 2 (2 instances): Cross-node aggregation, pod churn reduction
#
# Expected: ~10-50x reduction at Tier 1, additional 5-20x at Tier 2
# Dashboard: Processing Rules section shows per-rule input/output rates

services:
  # ---- Tier 1: DaemonSet edge pre-processing (3 instances) ----

  # Disable the default metrics-governor (replaced by tier1/tier2 instances)
  metrics-governor:
    profiles: ["disabled"]

  tier1-a:
    build: .
    ports:
      - "14317:4317"
      - "14318:4318"
      - "19091:9090"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    command:
      - "-exporter-endpoint=http://tier2-a:4317"
      - "-exporter-protocol=grpc"
      - "-exporter-insecure=true"
      - "-exporter-compression=zstd"
      - "-stats-labels=service,env"
      - "-processing-config=/etc/metrics-governor/processing-tier1.yaml"
      - "-flush-interval=100ms"
      - "-batch-size=100"
      - "-max-batch-bytes=4194304"
      - "-buffer-size=3000"
      - "-string-interning=true"
      - "-intern-max-value-length=64"
      - "-queue-enabled=true"
      - "-queue-type=memory"
      - "-queue-max-bytes=134217728"
      - "-queue-retry-interval=3s"
      - "-memory-limit-ratio=0.85"
    volumes:
      - ./examples/processing-tier1.yaml:/etc/metrics-governor/processing-tier1.yaml:ro
    depends_on:
      - tier2-a
      - tier2-b
    restart: on-failure

  tier1-b:
    build: .
    ports:
      - "24317:4317"
      - "24318:4318"
      - "29091:9090"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    command:
      - "-exporter-endpoint=http://tier2-b:4317"
      - "-exporter-protocol=grpc"
      - "-exporter-insecure=true"
      - "-exporter-compression=zstd"
      - "-stats-labels=service,env"
      - "-processing-config=/etc/metrics-governor/processing-tier1.yaml"
      - "-flush-interval=100ms"
      - "-batch-size=100"
      - "-max-batch-bytes=4194304"
      - "-buffer-size=3000"
      - "-string-interning=true"
      - "-intern-max-value-length=64"
      - "-queue-enabled=true"
      - "-queue-type=memory"
      - "-queue-max-bytes=134217728"
      - "-queue-retry-interval=3s"
      - "-memory-limit-ratio=0.85"
    volumes:
      - ./examples/processing-tier1.yaml:/etc/metrics-governor/processing-tier1.yaml:ro
    depends_on:
      - tier2-a
      - tier2-b
    restart: on-failure

  tier1-c:
    build: .
    ports:
      - "34317:4317"
      - "34318:4318"
      - "39091:9090"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
    command:
      - "-exporter-endpoint=http://tier2-a:4317"
      - "-exporter-protocol=grpc"
      - "-exporter-insecure=true"
      - "-exporter-compression=zstd"
      - "-stats-labels=service,env"
      - "-processing-config=/etc/metrics-governor/processing-tier1.yaml"
      - "-flush-interval=100ms"
      - "-batch-size=100"
      - "-max-batch-bytes=4194304"
      - "-buffer-size=3000"
      - "-string-interning=true"
      - "-intern-max-value-length=64"
      - "-queue-enabled=true"
      - "-queue-type=memory"
      - "-queue-max-bytes=134217728"
      - "-queue-retry-interval=3s"
      - "-memory-limit-ratio=0.85"
    volumes:
      - ./examples/processing-tier1.yaml:/etc/metrics-governor/processing-tier1.yaml:ro
    depends_on:
      - tier2-a
      - tier2-b
    restart: on-failure

  # ---- Tier 2: StatefulSet global aggregation (2 instances) ----

  tier2-a:
    build: .
    ports:
      - "44317:4317"
      - "44318:4318"
      - "49091:9090"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1"
    command:
      - "-exporter-endpoint=http://victoriametrics:8428/opentelemetry/v1/metrics"
      - "-exporter-protocol=http"
      - "-exporter-insecure=true"
      - "-exporter-compression=zstd"
      - "-stats-labels=service,env"
      - "-processing-config=/etc/metrics-governor/processing-tier2.yaml"
      - "-flush-interval=100ms"
      - "-batch-size=200"
      - "-max-batch-bytes=8388608"
      - "-buffer-size=5000"
      - "-string-interning=true"
      - "-intern-max-value-length=64"
      - "-queue-enabled=true"
      - "-queue-type=disk"
      - "-queue-path=/data/queue"
      - "-queue-max-bytes=1073741824"
      - "-queue-retry-interval=5s"
      - "-queue-full-behavior=drop_oldest"
      - "-queue-backoff-enabled=true"
      - "-queue-circuit-breaker-enabled=true"
      - "-queue-circuit-breaker-threshold=10"
      - "-memory-limit-ratio=0.85"
    volumes:
      - ./examples/processing-tier2.yaml:/etc/metrics-governor/processing-tier2.yaml:ro
      - tier2-a-queue:/data/queue
    depends_on:
      - victoriametrics
    restart: on-failure

  tier2-b:
    build: .
    ports:
      - "54317:4317"
      - "54318:4318"
      - "59091:9090"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "1"
    command:
      - "-exporter-endpoint=http://victoriametrics:8428/opentelemetry/v1/metrics"
      - "-exporter-protocol=http"
      - "-exporter-insecure=true"
      - "-exporter-compression=zstd"
      - "-stats-labels=service,env"
      - "-processing-config=/etc/metrics-governor/processing-tier2.yaml"
      - "-flush-interval=100ms"
      - "-batch-size=200"
      - "-max-batch-bytes=8388608"
      - "-buffer-size=5000"
      - "-string-interning=true"
      - "-intern-max-value-length=64"
      - "-queue-enabled=true"
      - "-queue-type=disk"
      - "-queue-path=/data/queue"
      - "-queue-max-bytes=1073741824"
      - "-queue-retry-interval=5s"
      - "-queue-full-behavior=drop_oldest"
      - "-queue-backoff-enabled=true"
      - "-queue-circuit-breaker-enabled=true"
      - "-queue-circuit-breaker-threshold=10"
      - "-memory-limit-ratio=0.85"
    volumes:
      - ./examples/processing-tier2.yaml:/etc/metrics-governor/processing-tier2.yaml:ro
      - tier2-b-queue:/data/queue
    depends_on:
      - victoriametrics
    restart: on-failure

  # ---- Override otel-collector to distribute across Tier 1 instances ----

  otel-collector:
    volumes:
      - ./test/otel-collector-config-two-tier.yaml:/etc/otelcol/config.yaml:ro
    depends_on:
      - tier1-a
      - tier1-b
      - tier1-c

  # ---- Generator: moderate load for processing visibility ----

  metrics-generator:
    environment:
      - OTLP_ENDPOINT=otel-collector:4317
      - METRICS_INTERVAL=200ms
      - SERVICES=payment-api,order-api,inventory-api,user-api,auth-api
      - ENVIRONMENTS=prod,staging,dev
      - ENABLE_EDGE_CASES=false
      - ENABLE_HIGH_CARDINALITY=true
      - ENABLE_BURST_TRAFFIC=false
      - ENABLE_DIVERSE_METRICS=true
      - HIGH_CARDINALITY_COUNT=100
      - DIVERSE_METRIC_COUNT=80
      - TARGET_METRICS_PER_SEC=10000
      - TARGET_DATAPOINTS_PER_SEC=20000
      - METRICS_PORT=9091

  # ---- Verifier: lower threshold since processing drops data intentionally ----

  verifier:
    environment:
      - VM_ENDPOINT=http://victoriametrics:8428
      - MG_ENDPOINT=http://tier2-a:9090
      - CHECK_INTERVAL=30s
      - VERIFICATION_METRIC=generator_verification_counter
      - PASS_THRESHOLD=50.0
      - METRICS_PORT=9092

  # ---- VictoriaMetrics: scrape all 5 governor instances ----

  victoriametrics:
    volumes:
      - ./test/vmscrape-config-two-tier.yaml:/etc/victoriametrics/scrape.yaml:ro

volumes:
  tier2-a-queue:
    driver: local
  tier2-b-queue:
    driver: local
